version: '3'
services:
  client:
    build: ./client
    ports:
      - "3300:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5500:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=mern-auth-users

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mern-auth-users
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:


# docker-compose up --build
